import os
import csv
import re
import requests
from datetime import datetime, timedelta, timezone
from dotenv import load_dotenv

load_dotenv()

API_KEY = os.getenv("YOUTUBE_API_KEY")

MAX_PER_LABEL = 300
DAYS_BACK = 30
OUT_FILE = "youtube_video_metadata.csv"

REAL_KEYWORDS = [
    '"street interview" -ai -avatar -generated',
    '"podcast interview" -ai -avatar -generated',
    '"news interview" -ai -avatar -generated',
    '"public speaking" -ai -avatar -generated',
    '"lecture" -ai -avatar -generated',
    '"press conference" -ai -avatar -generated',
    '"vlog talking" -ai -avatar -generated',
    '"people talking" -ai -avatar -generated',
]

AI_KEYWORDS = [
    '"ai avatar" talking',
    '"ai generated" talking video',
    '"digital human" speaking',
    '"virtual presenter" ai',
    '"ai spokesperson"',
    '"talking avatar" ai',
    '"synthesia avatar"',
    '"heygen avatar"',
    '"d-id avatar"',
    '"deepfake demo"',
    '"ai clone" speaking',
    '"virtual influencer" ai',
]


AI_SIGNALS = [
    "ai avatar",
    "ai-generated",
    "ai generated",
    "generated by ai",
    "synthetic video",
    "synthetic media",
    "digital human",
    "virtual presenter",
    "virtual influencer",
    "talking avatar",
    "ai spokesperson",
    "ai presenter",
    "ai clone",
    "voice clone",
    "deepfake",
    "face swap",
    "synthesia",
    "heygen",
    "d-id",
    "did avatar",
    "runway",
    "pika labs",
    "kling ai",
    "sora",
    "veo",
    "higgsfield",
    "akool",
    "elai",
    "colossyan",
]

REAL_SIGNALS = [
    "interview",
    "podcast",
    "lecture",
    "news interview",
    "news report",
    "street interview",
    "public speaking",
    "press conference",
    "conversation",
    "talk show",
    "vlog",
    "speaker",
    "speech",
    "seminar",
    "webinar",
    "classroom",
    "documentary",
]

AI_REJECT_FOR_REAL = [
    "ai",
    "artificial intelligence",
    "avatar",
    "generated",
    "synthetic",
    "deepfake",
    "virtual presenter",
    "digital human",
    "synthesia",
    "heygen",
    "d-id",
    "runway",
    "pika",
    "kling",
    "sora",
]

REAL_REJECT_FOR_AI = [
    "how to make",
    "tutorial",
    "review",
    "reaction",
    "explained",
    "news about ai",
    "ai news",
    "chatgpt",
    "openai",
    "midjourney",
    "stable diffusion",
]


def clean_text(text):
    text = text or ""
    text = text.lower()
    text = re.sub(r"\s+", " ", text)
    return text.strip()


def score_terms(text, terms):
    return sum(1 for term in terms if term in text)


def classify_video(title, description, channel_title, expected_label):
    text = clean_text(f"{title} {description} {channel_title}")

    ai_score = score_terms(text, AI_SIGNALS)
    real_score = score_terms(text, REAL_SIGNALS)

    ai_reject_score = score_terms(text, AI_REJECT_FOR_REAL)
    real_reject_score = score_terms(text, REAL_REJECT_FOR_AI)

    if expected_label == "ai":
        if ai_score >= 1 and real_reject_score == 0:
            return "ai"

        if ai_score >= 2:
            return "ai"

        return None

    if expected_label == "real":
        if real_score >= 1 and ai_reject_score == 0:
            return "real"

        if real_score >= 2 and ai_score == 0:
            return "real"

        return None

    return None


def youtube_search(query, page_token=None):
    published_after = (
        datetime.now(timezone.utc) - timedelta(days=DAYS_BACK)
    ).isoformat()

    params = {
        "part": "snippet",
        "key": API_KEY,
        "q": query,
        "type": "video",
        "maxResults": 50,
        "order": "date",
        "publishedAfter": published_after,
        "videoDuration": "short",
        "relevanceLanguage": "en",
        "safeSearch": "moderate",
    }

    if page_token:
        params["pageToken"] = page_token

    r = requests.get(
        "https://www.googleapis.com/youtube/v3/search",
        params=params,
        timeout=30
    )

    r.raise_for_status()
    return r.json()


def get_video_details(video_ids):
    if not video_ids:
        return []

    params = {
        "part": "snippet,contentDetails,statistics,status",
        "key": API_KEY,
        "id": ",".join(video_ids),
        "maxResults": 50
    }

    r = requests.get(
        "https://www.googleapis.com/youtube/v3/videos",
        params=params,
        timeout=30
    )

    r.raise_for_status()
    return r.json().get("items", [])


def save_rows(rows):
    fields = [
        "label",
        "keyword",
        "video_id",
        "title",
        "description",
        "channel_title",
        "published_at",
        "duration",
        "view_count",
        "like_count",
        "comment_count",
        "url"
    ]

    with open(OUT_FILE, "w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)


def collect(label, keywords):
    collected = []
    seen = set()

    for keyword in keywords:
        if len(collected) >= MAX_PER_LABEL:
            break

        print(f"\nCollecting {label}: {keyword}")

        page_token = None
        pages_checked = 0

        while len(collected) < MAX_PER_LABEL and pages_checked < 5:
            pages_checked += 1

            try:
                data = youtube_search(keyword, page_token)
            except Exception as e:
                print(f"Search failed for {keyword}: {e}")
                break

            ids = []

            for item in data.get("items", []):
                video_id = item.get("id", {}).get("videoId")

                if video_id and video_id not in seen:
                    seen.add(video_id)
                    ids.append(video_id)

            try:
                details = get_video_details(ids)
            except Exception as e:
                print(f"Details failed: {e}")
                break

            for video in details:
                if len(collected) >= MAX_PER_LABEL:
                    break

                snippet = video.get("snippet", {})
                stats = video.get("statistics", {})
                content = video.get("contentDetails", {})
                status = video.get("status", {})

                if status.get("privacyStatus") != "public":
                    continue

                title = snippet.get("title", "")
                description = snippet.get("description", "")
                channel_title = snippet.get("channelTitle", "")

                detected_label = classify_video(
                    title,
                    description,
                    channel_title,
                    label
                )

                if detected_label != label:
                    continue

                row = {
                    "label": label,
                    "keyword": keyword,
                    "video_id": video["id"],
                    "title": title,
                    "description": description,
                    "channel_title": channel_title,
                    "published_at": snippet.get("publishedAt", ""),
                    "duration": content.get("duration", ""),
                    "view_count": stats.get("viewCount", ""),
                    "like_count": stats.get("likeCount", ""),
                    "comment_count": stats.get("commentCount", ""),
                    "url": f"https://www.youtube.com/watch?v={video['id']}"
                }

                collected.append(row)
                print(f"[{label.upper()}] {len(collected)}/{MAX_PER_LABEL}: {title[:80]}")

            page_token = data.get("nextPageToken")

            if not page_token:
                break

    return collected


def main():
    if not API_KEY:
        raise RuntimeError("Missing YOUTUBE_API_KEY in .env")

    all_rows = []

    real_rows = collect("real", REAL_KEYWORDS)
    ai_rows = collect("ai", AI_KEYWORDS)

    all_rows.extend(real_rows)
    all_rows.extend(ai_rows)

    save_rows(all_rows)

    print("\nDone.")
    print(f"Saved {len(all_rows)} rows to {OUT_FILE}")
    print(f"Real: {len(real_rows)}")
    print(f"AI: {len(ai_rows)}")

    if len(real_rows) < MAX_PER_LABEL:
        print(f"Warning: only found {len(real_rows)} real videos.")

    if len(ai_rows) < MAX_PER_LABEL:
        print(f"Warning: only found {len(ai_rows)} AI videos.")


if __name__ == "__main__":
    main()